"""Add fields to post

Revision ID: 10c51206760d
Revises: 22b0b400b67a
Create Date: 2025-02-06 14:07:23.152240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c51206760d'
down_revision = '22b0b400b67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_post')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('starttime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('endtime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('isfinished', sa.Boolean(), nullable=False))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('isfinished')
        batch_op.drop_column('endtime')
        batch_op.drop_column('starttime')
        batch_op.drop_column('goal')

    op.create_table('_alembic_tmp_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=300), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('goal', sa.VARCHAR(length=60), nullable=False),
    sa.Column('starttime', sa.DATETIME(), nullable=False),
    sa.Column('endtime', sa.DATETIME(), nullable=False),
    sa.Column('isfinished', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
